idf_component_register(
    SRCS
        "app_main.c"
    EMBED_TXTFILES
        "${CMAKE_SOURCE_DIR}/../ESP32/keys/iot/AmazonRootCA1.pem"
        "${CMAKE_SOURCE_DIR}/../ESP32/keys/iot/device-cert.pem"
    INCLUDE_DIRS
        "."
    REQUIRES
        OS
        Middleware
        esp_component
        app_update
        bootloader_support
)
