@echo off
REM Generate RSA-2048 keypair for STM32 firmware signing

setlocal

set KEYS_DIR=..\ESP32\keys
set PRIVATE_KEY=%KEYS_DIR%\stm32_private_key.pem
set PUBLIC_KEY=%KEYS_DIR%\stm32_public_key.pem
set HEADER_FILE=..\ESP32\Middleware\Services\stm32_public_key.h

echo ==================================
echo STM32 RSA-2048 Key Generation
echo ==================================
echo.

REM Create keys directory if it doesn't exist
if not exist "%KEYS_DIR%" mkdir "%KEYS_DIR%"

REM Generate private key (2048 bits)
echo Generating RSA-2048 private key...
openssl genrsa -out "%PRIVATE_KEY%" 2048

if errorlevel 1 (
    echo Error: Failed to generate private key
    echo Make sure OpenSSL is installed and in your PATH
    pause
    exit /b 1
)

echo [32m✓ Private key generated: %PRIVATE_KEY%[0m
echo.

REM Extract public key
echo Extracting public key...
openssl rsa -in "%PRIVATE_KEY%" -pubout -out "%PUBLIC_KEY%"

if errorlevel 1 (
    echo Error: Failed to extract public key
    pause
    exit /b 1
)

echo [32m✓ Public key extracted: %PUBLIC_KEY%[0m
echo.

REM Display public key
echo Public Key (PEM format):
echo ------------------------
type "%PUBLIC_KEY%"
echo.

REM Create header file with embedded public key
echo Updating embedded public key in ESP32 firmware...

(
echo /**
echo  * @file stm32_public_key.h
echo  * @brief Embedded RSA Public Key for Firmware Verification
echo  *
echo  * This file contains the embedded RSA-2048 public key for firmware signature verification.
echo  *
echo  * Generated automatically by tools/generate_rsa_keys.bat
echo  * DO NOT edit this file manually - regenerate keys if needed.
echo  *
echo  * To generate a new RSA-2048 keypair:
echo  *   cd tools ^&^& generate_rsa_keys.bat
echo  */
echo.
echo #ifndef STM32_PUBLIC_KEY_H
echo #define STM32_PUBLIC_KEY_H
echo.
echo static const char stm32_public_key_pem[] =
) > "%HEADER_FILE%"

REM Append public key with C string formatting
for /f "delims=" %%i in (%PUBLIC_KEY%) do (
    echo "%%i\n">> "%HEADER_FILE%"
)

REM Close the header file
(
echo ;
echo.
echo #endif // STM32_PUBLIC_KEY_H
) >> "%HEADER_FILE%"

echo [32m✓ Header file updated: %HEADER_FILE%[0m
echo.

REM Verify the key
echo Verifying RSA key...
openssl rsa -in "%PRIVATE_KEY%" -check -noout

if errorlevel 0 (
    echo [32m✓ RSA key is valid[0m
) else (
    echo [31m✗ RSA key verification failed[0m
    pause
    exit /b 1
)

echo.
echo ==================================
echo Key Generation Complete!
echo ==================================
echo.
echo Files created:
echo   Private key: %PRIVATE_KEY% (KEEP SECRET!)
echo   Public key:  %PUBLIC_KEY%
echo   Header file: %HEADER_FILE% (embedded in ESP32)
echo.
echo [33m⚠️  IMPORTANT:[0m
echo   - Back up the private key securely
echo   - Never commit the private key to git (.gitignore is configured)
echo   - The public key is embedded in ESP32 firmware
echo   - Rebuild ESP32 firmware to use the new public key
echo.
echo Next steps:
echo   1. Rebuild ESP32 firmware: cd ESP32 ^&^& idf.py build
echo   2. Flash ESP32 with new firmware
echo   3. Sign STM32 firmware: python upload_firmware.py stm32-firmware.bin --platform stm32
echo.

pause
