#!/bin/bash
# Generate RSA-2048 keypair for STM32 firmware signing

KEYS_DIR="../ESP32/keys"
PRIVATE_KEY="$KEYS_DIR/stm32_private_key.pem"
PUBLIC_KEY="$KEYS_DIR/stm32_public_key.pem"
HEADER_FILE="../ESP32/Middleware/Services/stm32_public_key.h"

echo "=================================="
echo "STM32 RSA-2048 Key Generation"
echo "=================================="
echo ""

# Create keys directory if it doesn't exist
mkdir -p "$KEYS_DIR"

# Generate private key (2048 bits)
echo "Generating RSA-2048 private key..."
openssl genrsa -out "$PRIVATE_KEY" 2048

if [ $? -ne 0 ]; then
    echo "Error: Failed to generate private key"
    exit 1
fi

echo "✓ Private key generated: $PRIVATE_KEY"
echo ""

# Extract public key
echo "Extracting public key..."
openssl rsa -in "$PRIVATE_KEY" -pubout -out "$PUBLIC_KEY"

if [ $? -ne 0 ]; then
    echo "Error: Failed to extract public key"
    exit 1
fi

echo "✓ Public key extracted: $PUBLIC_KEY"
echo ""

# Display public key
echo "Public Key (PEM format):"
echo "------------------------"
cat "$PUBLIC_KEY"
echo ""

# Update header file
echo "Updating embedded public key in ESP32 firmware..."

cat > "$HEADER_FILE" << 'EOF'
/**
 * @file stm32_public_key.h
 * @brief Embedded RSA Public Key for Firmware Verification
 *
 * This file contains the embedded RSA-2048 public key for firmware signature verification.
 *
 * Generated automatically by tools/generate_rsa_keys.sh
 * DO NOT edit this file manually - regenerate keys if needed.
 *
 * To generate a new RSA-2048 keypair:
 *   cd tools && ./generate_rsa_keys.sh
 */

#ifndef STM32_PUBLIC_KEY_H
#define STM32_PUBLIC_KEY_H

static const char stm32_public_key_pem[] =
EOF

# Append the public key with proper C string formatting
while IFS= read -r line; do
    echo "\"$line\\n\"" >> "$HEADER_FILE"
done < "$PUBLIC_KEY"

# Close the header file
cat >> "$HEADER_FILE" << 'EOF'
;

#endif // STM32_PUBLIC_KEY_H
EOF

echo "✓ Header file updated: $HEADER_FILE"
echo ""

# Verify the key
echo "Verifying RSA key..."
openssl rsa -in "$PRIVATE_KEY" -check -noout

if [ $? -eq 0 ]; then
    echo "✓ RSA key is valid"
else
    echo "✗ RSA key verification failed"
    exit 1
fi

echo ""
echo "=================================="
echo "Key Generation Complete!"
echo "=================================="
echo ""
echo "Files created:"
echo "  Private key: $PRIVATE_KEY (KEEP SECRET!)"
echo "  Public key:  $PUBLIC_KEY"
echo "  Header file: $HEADER_FILE (embedded in ESP32)"
echo ""
echo "⚠️  IMPORTANT:"
echo "  - Back up the private key securely"
echo "  - Never commit the private key to git (.gitignore is configured)"
echo "  - The public key is embedded in ESP32 firmware"
echo "  - Rebuild ESP32 firmware to use the new public key"
echo ""
echo "Next steps:"
echo "  1. Rebuild ESP32 firmware: cd ESP32 && idf.py build"
echo "  2. Flash ESP32 with new firmware"
echo "  3. Sign STM32 firmware: ./upload_firmware.py stm32-firmware.bin --platform stm32"
echo ""
